name: CI - MLflow Training Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # ── 1. Checkout repository ────────────────────────────────
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ── 2. Setup Python ───────────────────────────────────────
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # ── 3. Install dependencies ───────────────────────────────
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib

      # ── 4. Run MLflow Project ─────────────────────────────────
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # ── 5. Upload artefak ke GitHub ───────────────────────────
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            MLProject/mlruns/
            MLProject/artifacts/
          retention-days: 7
